### ISSUE TITLE
Range check overlays

### ISSUE THREAD

**Issue by ozGremlin** [JohnnyCheese/TTS_X-Wing2.0#127]
Related to Issues #29 and #111.

1. The R1 overlay for bombs is not visible when using the top-down camera. 
2. Obstacles don't have range check overlays but do need them. (Placement and Seismic charges)
3. Bombs and obstacles need a graphical interface for accessing the range check.

**Comment by eirikmun** [comment]
1. Changed the r1 overlay to match the new style
2. The r1 for obstacles have been added on the beta
3. Bombs and obstacles now has a context menu for "Toggle R1 bubble"
