### ISSUE TITLE
Interceptor model won’t load

### ISSUE THREAD

**Issue by Michealff** [JohnnyCheese/TTS_X-Wing2.0#156]
Hi, I have tried a few time to import the interceptor from TTS and it fails every time, usual Soontir Fel. Is this a common occurs or have I missed something? It’s asking for me to import figurine! Thanks

**Comment by eirikmun** [comment]
A screenshot of any error message would be nice.
The assets are there, and nothing has changed, so it's likely a local problem. Hard to tell.

**Comment by Michealff** [comment]
Hi,

Not to worry. I think it is a local issue, it seems random but 5 minutes logged out seemed to sort it! Apologies for the over reaction. I can remove the post if necessary? Also thanks for getting back so quick! I expected a 3-5 days wait auto response email! Haha

Micheál

**Comment by eirikmun** [comment]
No problem.
Closing this now.
