### ISSUE TITLE
Bullseye arc checks includes nubs

### ISSUE THREAD

**Issue by mmedeirosgoncalves** [JohnnyCheese/TTS_X-Wing2.0#159]
![Bullseye Error](https://user-images.githubusercontent.com/30636216/84657224-57fcff80-aeea-11ea-9c7a-db33a8707077.jpg)

Chats says its on bulleye but on visual it is not

**Comment by eirikmun** [comment]
The nubs should be considered by the bullseye arc check.

**Comment by eirikmun** [comment]
Fixed
