### ISSUE TITLE
Ship doesn`t move

### ISSUE THREAD

**Issue by mmedeirosgoncalves** [JohnnyCheese/TTS_X-Wing2.0#167]
After set the dial and click on the manauver the ship stayed in it previous location.

I took few pictures from the error showed in our chat log.

![figu2](https://user-images.githubusercontent.com/30636216/85224452-e8cb5380-b3a0-11ea-9ddf-f59ced311809.jpg)
![Figu1](https://user-images.githubusercontent.com/30636216/85224454-e963ea00-b3a0-11ea-98c8-7cdd78549083.jpg)

**Comment by eirikmun** [comment]
Fixed now, with changes to the token module
