### ISSUE TITLE
Issue: DRK-1 Probe Droid Launch and Relocate

### ISSUE THREAD

**Issue by NahjoChe** [JohnnyCheese/TTS_X-Wing2.0#214]
DRK-1 Probe droids do not launch/drop/relocate with the correct distances/angles.
Distances off by up to half a base width.

The 2 straight relocate looks about right, none of the others do.

Please see screenshot below.
![DRK_Issue](https://user-images.githubusercontent.com/70908471/92405207-b17e6e80-f167-11ea-91b3-63a048187b66.png)

**Comment by eirikmun** [comment]
Adjusted the launch problems. The bank relocate didn't seem to far off. Will take a look at it again.

**Comment by eirikmun** [comment]
Fixed

**Comment by eirikmun** [comment]
w
