### ISSUE TITLE
Issue: Unable to spawn lists containing "Deadman's Switch" (illicit)

### ISSUE THREAD

**Issue by Taloncor** [JohnnyCheese/TTS_X-Wing2.0#252]
When trying to spawn a list that contains the _Deadman's Switch_ upgrade, the following error message is shown and the list will not be spawned.
```
Error in Script (DataPad - a4bbf) function <builderSpawn>: chunk_3:(1079,12 - 183): attempt to concatenate a nil value
```

How to reproduce (example):
1. Use the built-in Builder
2. Pick Rebel
3. Add Ship
  1. X-Wing (Cavern Angels Zealot)
  2. Add illicit upgrade _Deadman's Switch_ 
4. Spawn List

**Comment by eirikmun** [comment]
This is fixed
