### ISSUE TITLE
Add epic content to the builder

### ISSUE THREAD

**Issue by eirikmun** [JohnnyCheese/TTS_X-Wing2.0#69]

**Comment by PsyonicReign** [comment]
Ordnance Tubes, Point-Defense Battery, Ordnance Team, & Suppressor are misspelled.
Jan Dodonna is listed twice, while Raymus Antilles & Strategic Commander are missing.
All ships need a Command slot for upgrade options: Agent of the Empire, Dreadnought Hunter, First Order Elite, & Veteran Wing Leader.
